CC = gcc
CFLAGS = -O2 -Wall -Wextra -pthread
LDFLAGS = -lm

TARGET = multiplicacao_matrizes
SRC = src/multiplicacao_matrizes.c

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) $(SRC) -o $(TARGET) $(LDFLAGS)

run: $(TARGET)
	./$(TARGET)

clean:
	rm -f $(TARGET)

.PHONY: all run clean
